#pragma once
#include "hw.h"

#define DEVICE_NAME "pio-weather"

#define DHT_SENSOR_ENABLED 1
#define DHT_SENSOR_IS_DHT22 0
#define DHT_READ_INTERVAL_MS 15000

#define WEATHER_REPORT_ENABLED 1
#define WEATHER_AREA_INDEX 1
#define WEATHER_REPORT_INTERVAL_MS 3600000
#define WEATHER_PROXY_REQUEST_INTERVAL_MS 3600000

#define ENABLE_POWERSAVE 0